# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import flight_pb2 as flight__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in flight_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FlightServiceStub(object):
    """Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchFlights = channel.unary_unary(
                '/flight.FlightService/SearchFlights',
                request_serializer=flight__pb2.SearchFlightsRequest.SerializeToString,
                response_deserializer=flight__pb2.SearchFlightsResponse.FromString,
                _registered_method=True)
        self.GetFlight = channel.unary_unary(
                '/flight.FlightService/GetFlight',
                request_serializer=flight__pb2.GetFlightRequest.SerializeToString,
                response_deserializer=flight__pb2.GetFlightResponse.FromString,
                _registered_method=True)
        self.ReserveSeats = channel.unary_unary(
                '/flight.FlightService/ReserveSeats',
                request_serializer=flight__pb2.ReserveSeatsRequest.SerializeToString,
                response_deserializer=flight__pb2.ReserveSeatsResponse.FromString,
                _registered_method=True)
        self.ReleaseReservation = channel.unary_unary(
                '/flight.FlightService/ReleaseReservation',
                request_serializer=flight__pb2.ReleaseReservationRequest.SerializeToString,
                response_deserializer=flight__pb2.ReleaseReservationResponse.FromString,
                _registered_method=True)


class FlightServiceServicer(object):
    """Service
    """

    def SearchFlights(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFlight(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReserveSeats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseReservation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FlightServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchFlights': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchFlights,
                    request_deserializer=flight__pb2.SearchFlightsRequest.FromString,
                    response_serializer=flight__pb2.SearchFlightsResponse.SerializeToString,
            ),
            'GetFlight': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFlight,
                    request_deserializer=flight__pb2.GetFlightRequest.FromString,
                    response_serializer=flight__pb2.GetFlightResponse.SerializeToString,
            ),
            'ReserveSeats': grpc.unary_unary_rpc_method_handler(
                    servicer.ReserveSeats,
                    request_deserializer=flight__pb2.ReserveSeatsRequest.FromString,
                    response_serializer=flight__pb2.ReserveSeatsResponse.SerializeToString,
            ),
            'ReleaseReservation': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseReservation,
                    request_deserializer=flight__pb2.ReleaseReservationRequest.FromString,
                    response_serializer=flight__pb2.ReleaseReservationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'flight.FlightService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('flight.FlightService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FlightService(object):
    """Service
    """

    @staticmethod
    def SearchFlights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flight.FlightService/SearchFlights',
            flight__pb2.SearchFlightsRequest.SerializeToString,
            flight__pb2.SearchFlightsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFlight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flight.FlightService/GetFlight',
            flight__pb2.GetFlightRequest.SerializeToString,
            flight__pb2.GetFlightResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReserveSeats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flight.FlightService/ReserveSeats',
            flight__pb2.ReserveSeatsRequest.SerializeToString,
            flight__pb2.ReserveSeatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseReservation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flight.FlightService/ReleaseReservation',
            flight__pb2.ReleaseReservationRequest.SerializeToString,
            flight__pb2.ReleaseReservationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
