version: '3.8'

services:

  flight-service:
    build: ./flight_service
    container_name: flight_service
    ports:
      - "50051:50051"
    environment:
      - DATABASE_URL=postgresql://flight_user:flight_password@flight_db:5432/flight_db
    depends_on:
      - flight_db

  booking-service:
    build: ./booking_service
    container_name: booking_service
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://booking_user:booking_password@booking_db:5432/booking_db
    depends_on:
      - booking_db
      - flight-service

  flight_db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: flight_user
      POSTGRES_PASSWORD: flight_password
      POSTGRES_DB: flight_db
      PGDATA: /var/lib/postgresql/data/new_flight_data
    ports:
      - "5432:5432"
  
  flight_flyway:
    image: flyway/flyway:9-alpine
    command: -url=jdbc:postgresql://flight_db:5432/flight_db -user=flight_user -password=flight_password -connectRetries=60 migrate
    volumes:
      - ./flight_service/db/migrations:/flyway/sql
    depends_on:
      - flight_db

  booking_db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: booking_user
      POSTGRES_PASSWORD: booking_password
      POSTGRES_DB: booking_db
      PGDATA: /var/lib/postgresql/data/new_booking_data
    ports:
      - "5433:5432"
  
  booking_flyway:
    image: flyway/flyway:9-alpine
    command: -url=jdbc:postgresql://booking_db:5432/booking_db -user=booking_user -password=booking_password -connectRetries=60 migrate
    volumes:
      - ./booking_service/db/migrations:/flyway/sql
    depends_on:
      - booking_db
  
